# Generated by Django 3.1.1 on 2020-09-04 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Hora')),
                ('seat_number', models.PositiveSmallIntegerField(verbose_name='Cadira')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Preu')),
                ('status', models.CharField(choices=[('received', 'received'), ('preparing', 'preparing'), ('on_delivery', 'on_delivery'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='received', max_length=32, verbose_name='estat')),
                ('payment_method', models.CharField(choices=[('card', 'card'), ('cash', 'cash')], default='card', max_length=16, verbose_name='Pagament')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preu')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantitat')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Preu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producte')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
    ]
